# Generated by Django 4.1.1 on 2022-09-29 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('isActive', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('isActive', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_caption', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_django_backend.user')),
            ],
        ),
    ]
