# Generated by Django 4.1.1 on 2022-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('isActive', models.CharField(max_length=20)),
            ],
        ),
    ]
